import json
import joblib
import pandas as pd

from pathlib import Path


# =========================================================
# 1. PROJECT PATHS
# =========================================================

# Project root:
# D:\Enterprise_ITSM_AI

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent

MODELS_DIR = PROJECT_ROOT / "models_saved"

DATA_DIR = PROJECT_ROOT / "data" / "raw"


# =========================================================
# 2. FILE PATHS
# =========================================================

ASSIGNMENT_MODEL_PATH = (
    MODELS_DIR / "assignment_group_prediction_pipeline.joblib"
)

ASSIGNMENT_ENCODER_PATH = (
    MODELS_DIR / "assignment_group_label_encoder.joblib"
)

INCIDENT_DATA_PATH = (
    DATA_DIR /"itsm_cleaned_dataset.csv"
)


# =========================================================
# 3. LOAD ASSIGNMENT GROUP MODEL
# =========================================================

print("\n====================================")
print("LOADING AGENT 2")
print("====================================")

try:

    assignment_group_model = joblib.load(
        ASSIGNMENT_MODEL_PATH
    )

    assignment_group_encoder = joblib.load(
        ASSIGNMENT_ENCODER_PATH
    )

    print("Assignment Group model loaded successfully!")

except Exception as e:

    print("\nERROR: Could not load Assignment Group model.")

    print(e)

    raise


# =========================================================
# 4. LOAD INCIDENT DATASET
# =========================================================

try:

    df = pd.read_csv(
        INCIDENT_DATA_PATH
    )

    print(
        f"Incident dataset loaded successfully!"
        f"\nShape: {df.shape}"
    )

except Exception as e:

    print("\nERROR: Could not load incident dataset.")

    print(e)

    raise


# =========================================================
# 5. PREPARE RESOLVER HISTORY
# =========================================================

print("\nPreparing resolver history...")


# Remove incidents where assignment group or resolver
# information is missing.

resolver_history = df.dropna(
    subset=[
        "assignment_group",
        "resolved_by"
    ]
).copy()


# ---------------------------------------------------------
# Count how many incidents each resolver handled
# inside each assignment group.
# ---------------------------------------------------------

resolver_mapping = (
    resolver_history
    .groupby(
        [
            "assignment_group",
            "resolved_by"
        ]
    )
    .size()
    .reset_index(
        name="incident_count"
    )
)


# ---------------------------------------------------------
# Sort:
# highest historical workload first
# ---------------------------------------------------------

resolver_mapping = (
    resolver_mapping
    .sort_values(
        [
            "assignment_group",
            "incident_count"
        ],
        ascending=[
            True,
            False
        ]
    )
)


print(
    "Resolver history prepared successfully!"
)

print(
    f"Unique assignment groups in resolver history: "
    f"{resolver_mapping['assignment_group'].nunique()}"
)

print(
    f"Unique resolvers in resolver history: "
    f"{resolver_mapping['resolved_by'].nunique()}"
)


# =========================================================
# 6. PREDICT ASSIGNMENT GROUP
# =========================================================

def predict_assignment_group(
    features: dict
):
    """
    Predict the assignment group for an incident.

    Parameters
    ----------
    features : dict
        Validated ML features generated by Agent 1.

    Returns
    -------
    str
        Predicted assignment group.
    """

    feature_df = pd.DataFrame(
        [features]
    )

    prediction = assignment_group_model.predict(
        feature_df
    )[0]

    predicted_group = (
        assignment_group_encoder
        .inverse_transform(
            [prediction]
        )[0]
    )

    return predicted_group


# =========================================================
# 7. GET TOP RESOLVERS
# =========================================================

def get_top_resolvers(
    assignment_group: str,
    top_n: int = 3
):
    """
    Find the most frequently used resolvers
    for the predicted assignment group.
    """

    group_history = resolver_mapping[
        resolver_mapping["assignment_group"]
        == assignment_group
    ].copy()


    # -----------------------------------------------------
    # No resolver history
    # -----------------------------------------------------

    if group_history.empty:

        return []


    # -----------------------------------------------------
    # Make sure highest count comes first
    # -----------------------------------------------------

    group_history = group_history.sort_values(
        "incident_count",
        ascending=False
    )


    # -----------------------------------------------------
    # Return top N
    # -----------------------------------------------------

    top_resolvers = (
        group_history
        .head(top_n)
        .to_dict(
            orient="records"
        )
    )

    return top_resolvers


# =========================================================
# 8. COMPLETE AGENT 2
# =========================================================

def intelligent_assignment(
    features: dict,
    top_n: int = 3
):
    """
    Complete Agent 2 workflow.

    1. Predict assignment group.
    2. Find historical resolver candidates.
    3. Rank candidates.
    4. Return recommendation.
    """

    # -----------------------------------------------------
    # STEP 1 — Predict assignment group
    # -----------------------------------------------------

    predicted_group = predict_assignment_group(
        features
    )


    # -----------------------------------------------------
    # STEP 2 — Find historical resolvers
    # -----------------------------------------------------

    top_resolvers = get_top_resolvers(
        predicted_group,
        top_n
    )


    # -----------------------------------------------------
    # STEP 3 — Select recommended resolver
    # -----------------------------------------------------

    if top_resolvers:

        recommended_resolver = (
            top_resolvers[0]["resolved_by"]
        )

    else:

        recommended_resolver = None


    # -----------------------------------------------------
    # STEP 4 — Return result
    # -----------------------------------------------------

    return {

        "predicted_assignment_group":
            predicted_group,

        "recommended_resolver":
            recommended_resolver,

        "alternative_resolvers":
            top_resolvers,

        "resolver_history_available":
            len(top_resolvers) > 0
    }


# =========================================================
# 9. TEST AGENT 2
# =========================================================

if __name__ == "__main__":

    print("\n====================================")
    print("AGENT 2 — INTELLIGENT ASSIGNMENT")
    print("====================================")


    # -----------------------------------------------------
    # Test features
    #
    # These are the same type of features produced
    # by Agent 1.
    # -----------------------------------------------------

    test_features = {

        "contact_type":
            "Self-service",

        "location":
            "Location 1",

        "u_symptom":
            "Symptom 1",

        "impact":
            "2 - Medium",

        "urgency":
            "2 - Medium",

        "knowledge":
            False,

        "notify":
            "Do Not Notify",

        "opened_hour":
            10,

        "opened_day_of_week":
            2,

        "opened_month":
            8,

        "is_weekend":
            False
    }


    # -----------------------------------------------------
    # Run Agent 2
    # -----------------------------------------------------

    try:

        result = intelligent_assignment(
            test_features,
            top_n=3
        )


        # -------------------------------------------------
        # Display results
        # -------------------------------------------------

        print("\nPredicted Assignment Group:")
        print(
            result[
                "predicted_assignment_group"
            ]
        )


        print("\nRecommended Resolver:")

        print(
            result[
                "recommended_resolver"
            ]
        )


        print("\nAlternative Resolvers:")

        for index, resolver in enumerate(
            result[
                "alternative_resolvers"
            ],
            start=1
        ):

            print(
                f"{index}. "
                f"{resolver['resolved_by']} "
                f"("
                f"{resolver['incident_count']} "
                f"historical incidents"
                f")"
            )


        print(
            "\nResolver History Available:"
        )

        print(
            result[
                "resolver_history_available"
            ]
        )


        print("\n====================================")
        print("AGENT 2 COMPLETED SUCCESSFULLY")
        print("====================================")


    except Exception as e:

        print("\n====================================")
        print("AGENT 2 FAILED")
        print("====================================")

        print(
            str(e)
        )

        print("\n====================================")